package com.gyg.beans;

public class Cat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.id
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.cName
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.cAge
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    private Integer cage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.cGender
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    private Integer cgender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.id
     *
     * @return the value of t_cat.id
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.id
     *
     * @param id the value for t_cat.id
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.cName
     *
     * @return the value of t_cat.cName
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.cName
     *
     * @param cname the value for t_cat.cName
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.cAge
     *
     * @return the value of t_cat.cAge
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public Integer getCage() {
        return cage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.cAge
     *
     * @param cage the value for t_cat.cAge
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public void setCage(Integer cage) {
        this.cage = cage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.cGender
     *
     * @return the value of t_cat.cGender
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public Integer getCgender() {
        return cgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.cGender
     *
     * @param cgender the value for t_cat.cGender
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public void setCgender(Integer cgender) {
        this.cgender = cgender;
    }
}