package com.gyg.beans;

import java.util.ArrayList;
import java.util.List;

public class CatExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public CatExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCnameIsNull() {
            addCriterion("cName is null");
            return (Criteria) this;
        }

        public Criteria andCnameIsNotNull() {
            addCriterion("cName is not null");
            return (Criteria) this;
        }

        public Criteria andCnameEqualTo(String value) {
            addCriterion("cName =", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotEqualTo(String value) {
            addCriterion("cName <>", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThan(String value) {
            addCriterion("cName >", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThanOrEqualTo(String value) {
            addCriterion("cName >=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThan(String value) {
            addCriterion("cName <", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThanOrEqualTo(String value) {
            addCriterion("cName <=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLike(String value) {
            addCriterion("cName like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotLike(String value) {
            addCriterion("cName not like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameIn(List<String> values) {
            addCriterion("cName in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotIn(List<String> values) {
            addCriterion("cName not in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameBetween(String value1, String value2) {
            addCriterion("cName between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotBetween(String value1, String value2) {
            addCriterion("cName not between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCageIsNull() {
            addCriterion("cAge is null");
            return (Criteria) this;
        }

        public Criteria andCageIsNotNull() {
            addCriterion("cAge is not null");
            return (Criteria) this;
        }

        public Criteria andCageEqualTo(Integer value) {
            addCriterion("cAge =", value, "cage");
            return (Criteria) this;
        }

        public Criteria andCageNotEqualTo(Integer value) {
            addCriterion("cAge <>", value, "cage");
            return (Criteria) this;
        }

        public Criteria andCageGreaterThan(Integer value) {
            addCriterion("cAge >", value, "cage");
            return (Criteria) this;
        }

        public Criteria andCageGreaterThanOrEqualTo(Integer value) {
            addCriterion("cAge >=", value, "cage");
            return (Criteria) this;
        }

        public Criteria andCageLessThan(Integer value) {
            addCriterion("cAge <", value, "cage");
            return (Criteria) this;
        }

        public Criteria andCageLessThanOrEqualTo(Integer value) {
            addCriterion("cAge <=", value, "cage");
            return (Criteria) this;
        }

        public Criteria andCageIn(List<Integer> values) {
            addCriterion("cAge in", values, "cage");
            return (Criteria) this;
        }

        public Criteria andCageNotIn(List<Integer> values) {
            addCriterion("cAge not in", values, "cage");
            return (Criteria) this;
        }

        public Criteria andCageBetween(Integer value1, Integer value2) {
            addCriterion("cAge between", value1, value2, "cage");
            return (Criteria) this;
        }

        public Criteria andCageNotBetween(Integer value1, Integer value2) {
            addCriterion("cAge not between", value1, value2, "cage");
            return (Criteria) this;
        }

        public Criteria andCgenderIsNull() {
            addCriterion("cGender is null");
            return (Criteria) this;
        }

        public Criteria andCgenderIsNotNull() {
            addCriterion("cGender is not null");
            return (Criteria) this;
        }

        public Criteria andCgenderEqualTo(Integer value) {
            addCriterion("cGender =", value, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderNotEqualTo(Integer value) {
            addCriterion("cGender <>", value, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderGreaterThan(Integer value) {
            addCriterion("cGender >", value, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("cGender >=", value, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderLessThan(Integer value) {
            addCriterion("cGender <", value, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderLessThanOrEqualTo(Integer value) {
            addCriterion("cGender <=", value, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderIn(List<Integer> values) {
            addCriterion("cGender in", values, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderNotIn(List<Integer> values) {
            addCriterion("cGender not in", values, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderBetween(Integer value1, Integer value2) {
            addCriterion("cGender between", value1, value2, "cgender");
            return (Criteria) this;
        }

        public Criteria andCgenderNotBetween(Integer value1, Integer value2) {
            addCriterion("cGender not between", value1, value2, "cgender");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cat
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 30 08:51:49 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cat
     *
     * @mbggenerated Fri Jul 30 08:51:49 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}